// Generated by Wrangler by running `wrangler types`

interface Env {
	SECRET_TELEGRAM_API_TOKEN: string;
	OPENAI_API_KEY: string;
	ANTHROPIC_API_KEY?: string;
	GEMINI_API_KEY?: string;
	account_id: string;
	DB: D1Database;
	OWNER_ID: string;
}
