// Generated by Wrangler by running `wrangler types`

interface Env {
	SECRET_TELEGRAM_API_TOKEN: string;
	OPENAI_API_KEY: string;
	ANTHROPIC_API_KEY?: string;
	GEMINI_API_KEY?: string;
	WORKER_AI_TOKEN: string;
	CF_ACCOUNT_ID: string;
	AI_GATEWAY_ID: string;
	R2_PUBLIC_URL: string;
	AI: Ai;
	DB: D1Database;
	SUMMARY_IMAGES: R2Bucket;
	OWNER_ID: string;
}
